### ISSUE TITLE
Small glitches

### ISSUE THREAD

**Issue by sbrl** [humberlora/humberlora.github.io#1]
Hey, great website! I spotted this in my GitHub activity feed and just had to check it out. I noticed a few small glitches though:

There's a typo in the view all posts button:

![](https://i.imgur.com/3XRupEL.png)

The map near the bottom looks like it's in development mode:

![image](https://user-images.githubusercontent.com/9929737/61585277-9c9fdf80-ab4f-11e9-9421-2d8c8a474d79.png)

Overall though it's a really cool website! I didn't we had so many gateways already.

**Comment by CrazyRobMiles** [comment]
Hi. Glad you like it. It's really only in test at the moment.  I've been
playing with the Hugo static site generator and some of the templates you
can get to see how close I can get to a nice looking site.    The figures
are all made up......

I'm going to tidy it up a bit more and then properly launch it with less
fictional numbers....

best wishes

Rob Miles

**Comment by CrazyRobMiles** [comment]
I've fixed the numbers to make them a bit more credible, removed the contact map (we don't really need it) and removed the typo.

**Comment by sbrl** [comment]
Ah, cool! I didn't know that the hugo static site generator could do all this. I'll have to check it out myself!
